matter-labs/zksync-protocol

Cargo.toml, RELEASE.md, crates/circuit_definitions/Cargo.toml, crates/circuit_encodings/Cargo.toml, crates/circuit_sequencer_api/Cargo.toml, crates/kzg/Cargo.toml, crates/zkEVM-assembly/Cargo.toml, crates/zk_evm/Cargo.toml, crates/zk_evm_abstractions/Cargo.toml, crates/zkevm_circuits/Cargo.toml, crates/zkevm_opcode_defs/Cargo.toml, crates/zkevm_test_harness/Cargo.toml
- Set the `workspace.version` for every crate, so that it's defined in one place.
- Bump the version to `0.150.4`
- Add `RELEASE.md` with release instructions.
=> Prepare 0.150.4 release

RELEASE.md
=> [skip ci] Update release notes

.github/workflows/ci.yaml
Allows faster interactions with repo configuration.
=> ci: Only run main CI if code changed

crates/zkEVM-assembly/src/assembly/linking/mod.rs, crates/zk_evm/src/lib.rs, crates/zk_evm/src/opcodes/execution/far_call.rs, crates/zk_evm/src/opcodes/execution/log.rs, crates/zk_evm/src/opcodes/execution/near_call.rs, crates/zk_evm/src/opcodes/execution/sub.rs, crates/zk_evm/src/opcodes/execution/uma.rs, crates/zk_evm/src/utils.rs, crates/zk_evm/src/vm_state/cycle.rs, crates/zk_evm/src/vm_state/helpers.rs, crates/zk_evm/src/vm_state/mod.rs, crates/zkevm_test_harness/src/lib.rs, crates/zkevm_test_harness/src/witness/individual_circuits/storage_sort_dedup.rs
- Fixes all the "red" errors (deny by default) observable in the monorepo.
- Fixes/silences _some_ of the "yellow" errors (there are just too many for a single PR).
The ultimate goal is to enable clippy in CI.
=> fix: Fix hard static analysis errors

.github/workflows/release-please-prepare-branch.yml, .github/workflows/release-please.yml
Implements two workflows:
- One to automatically change versions in `Cargo.toml` in the release branch (so that we see what we're going to release before we merge).
- One to publish packages on `crates.io`.
=> feat(ci): Automatic releases on crates.io

.github/workflows/release-please-prepare-branch.yml, .github/workflows/release-please.yml
- Fix echoing outputs
- Fix extracting version (PR title is not available on `push` trigger, so I'm reading manifest -- it's also safer).
=> chore(ci): Fix release-please workflows

.github/workflows/release-please.yml
Correctly pass outputs (cannot pass mapping, have to encode to json), and correctly escape json before `echo`
=> chore(ci): Fix release-please workflows #2

.github/workflows/release-please-prepare-branch.yml
Use `jq -r` to remove quotes from version, so that `cargo ws` can parse it.
=> chore(ci): Fix release-please workflows #3

Cargo.toml, crates/circuit_definitions/Cargo.toml, crates/circuit_encodings/Cargo.toml, crates/circuit_sequencer_api/Cargo.toml, crates/kzg/Cargo.toml, crates/zkEVM-assembly/Cargo.toml, crates/zk_evm/Cargo.toml, crates/zk_evm_abstractions/Cargo.toml, crates/zkevm_circuits/Cargo.toml, crates/zkevm_opcode_defs/Cargo.toml, crates/zkevm_test_harness/Cargo.toml
Set the fields from the workspace `Cargo.toml` and fix the GitHub URLs.
=> chore: Consistently set meta fields in Cargo.toml

crates/zkevm_test_harness/src/witness/utils.rs
Reduces the amount of unnecessary calculations, will reduce the BWG time by a second or two
=> fix: Simplify closed_form_witness_from_full_form

RELEASE.md
Adds documentation on how to make releases for old versions of the code.
Also ports the info on automatic releases from other monorepos.
=> docs: Document releasing old versions

crates/zkevm_test_harness/src/witness/oracle.rs, crates/zkevm_test_harness/src/witness/tracer/callstack_handler.rs
Using Box for big enum variant significantly reduces unnecessary memory usage by the tracer during witgen.
=> fix(zkevm_test_harness): Reduce ExtendedLogQuery RAM usage

crates/circuit_encodings/src/lib.rs, crates/zkevm_test_harness/src/tests/complex_tests/mod.rs, crates/zkevm_test_harness/src/tests/run_manually.rs, crates/zkevm_test_harness/src/witness/individual_circuits/memory_related/ram_permutation.rs, crates/zkevm_test_harness/src/witness/oracle.rs
Since queue states ([F; SW] part of witness)​​ aren't actually used by RAM permutation circuit, we can remove this RAM-heavy data from witness for this type of circuits.
This PR is first part of this change, which aims to be backwards compatible with current proving subsystem. Another PR that breaks backwards compatibility will contain removal of this field from the RAM witness completely.
=> feat: Use zeroes instead of simulator states as unused part of RAM permutation witness

crates/zkevm_test_harness/Cargo.toml, crates/zkevm_test_harness/src/tests/utils/preprocess_asm.rs
The `std::str::pattern::Pattern` trait implementation in the `regex` crate recently broke compilation with the nightly rust toolchain.
The removal of the trait implementation and the corresponding `pattern` feature is being [planned](https://github.com/rust-lang/regex/issues/1233). 
This PR removes the reliance on this trait implementation.
=> fix: remove the need for the `regex` crate's `pattern` feature

Cargo.toml
This PR bumps crypto crates to 0.30.2 to include https://github.com/matter-labs/zksync-crypto/pull/31
=> chore: bump crypto crates to 0.30.2

Cargo.toml
=> chore: bump crypto crates to 0.30.7

crates/circuit_definitions/src/circuit_definitions/aux_layer/compression_modes/mode_4.rs, crates/circuit_definitions/src/circuit_definitions/aux_layer/compression_modes/mode_5_for_wrapper.rs
This PR adjusts proof configs for compression circuits to improve proving speed.
=> perf(circuit_definitions): adjust proof configs for compression circuits

crates/zkevm_test_harness/src/compute_setups/full.rs, crates/zkevm_test_harness/src/compute_setups/mod.rs, crates/zkevm_test_harness/src/tests/complex_tests/mod.rs
* Adapt it to handle the basic_circuits that come out of order
* create VKs for basic circuits that were not generated by test.json file
* combine proofs for recursive_tip using BaseLayer iter explicitly.
=> fix: Fixing complex_test

crates/zkevm_test_harness/src/tests/complex_tests/mod.rs, crates/zkevm_test_harness/src/tests/complex_tests/precompiles.rs, crates/zkevm_test_harness/src/witness/mod.rs
Added test that covers both in & out of circuit, and runs in ~100 seconds.
To run:
```
cargo test --lib --release -- --test  ec_pairing_test  --nocapture
```
=> feat: Added tests for in&out circuit ecpairing

crates/zkevm_circuits/src/bn254/ec_pairing/alternative_pairing.rs, crates/zkevm_circuits/src/bn254/ec_pairing/alternative_precompile_naive.rs
Cover exception cases: 
- G1 infinity point, the result should be zero, and the point should be masked 
- G2 infinity point, the result should be zero, and the point should be masked 
- G1 and G2 are not on the curve; the result should be masked, but success should be true 
Fixed bugs: 
- bug in subgroup check 
- bug in Oracle 
- Pairing did not correctly handle infinity points
=> feat:  Bug fixing + tests

Cargo.lock, crates/zkevm_opcode_defs/Cargo.toml
- Bumps `sha2` dep from 10.8 to latest 10.9 
- Reasoning: `foundry-zksync` does weekly upstream merges from `foundry`. The foundry team recently bumped sha2 to 10.9 disrupting the weekly upstream process for `foundry-zksync`.
=> chore: bumps sha2 to latest 10.9 due to downstream requirement
